CREATE TABLE IF NOT EXISTS table_3 (table_3_c0 , table_3_c1  ) ;
INSERT INTO table_3 (table_3_c0, table_3_c1) VALUES (-2, NULL) ;
 ;
 ;
;;
;;
 ;
 ;
 ;
 ;
;;
 ;
 ;
 ;
;;
 ;
;;
 SELECT DISTINCT * FROM table_3  WHERE EXISTS ( SELECT  table_3_c1 FROM table_3 LIMIT NULL ) ;