CREATE TABLE T1(c1 , c2  );
CREATE TABLE T2(c1     );
CREATE TABLE T3( c2  );
SELECT (SELECT ROW_NUMBER() OVER (ORDER BY c.c2) FROM T3 ), DENSE_RANK() OVER () FROM T1 AS a INNER JOIN T2 AS b  INNER JOIN T3 AS c  WHERE a.c2 > c.c2 AND b.c1 > a.c1 GROUP BY a.c2;