CREATE TABLE photo (pk INTEGER PRIMARY KEY);
CREATE TABLE tag (pk INTEGER PRIMARY KEY, fk INTEGER);
INSERT INTO photo VALUES (1);
INSERT INTO tag VALUES (21, 1);
SELECT P.pk FROM PHOTO AS P WHERE EXISTS(SELECT T2.pk FROM TAG AS T2 WHERE T2.fk = P.pk EXCEPT SELECT T3.pk FROM TAG AS T3 WHERE T3.fk = P.pk);