import os
import random
import sqlglot
import sqlglot.errors
from loguru import logger
from sqlglot import exp
from .executor import SQLiteDifferentialExecutor, ExecutionResult
from .mutator import ASTMutator
from .logger import setup_logging
from .performance_statistics import get_performance_stats
from .query_statistics import QueryStatistics
from .coverage import FastCoverageTracker, run_final_lcov_evaluation
from .display import StatsDisplay

import logging
logging.getLogger("sqlglot").setLevel(logging.ERROR)

# Since we are avoiding two separate builds, we use the gcov-instrumented 
# binary for both bug finding (differential testing) and coverage guidance.
SQLITE_PATCHED_VERSION_PATH = "/home/test/sqlite3-src/sqlite3"
SQLITE_ORIGINAL_VERSION_PATH = "/usr/bin/sqlite3"
SEED_DIR = "./seeds"
SQL_DIALECT = "sqlite"

class SQLFuzzer:
    def __init__(self, seed_dir: str = SEED_DIR):
        self.seed_dir = seed_dir
        self.executor = SQLiteDifferentialExecutor(SQLITE_PATCHED_VERSION_PATH, SQLITE_ORIGINAL_VERSION_PATH)
        self.mutator = ASTMutator(dialect=SQL_DIALECT)
        self.corpus: list[tuple[str, str]] = []
        self.generated_queries: set[str] = set()
        self.statistics = QueryStatistics()
        # Path to the gcda file generated by the gcov-instrumented SQLite
        self.gcda_path = "/home/test/sqlite3-src/sqlite3-sqlite3.gcda"
        self.coverage_tracker = FastCoverageTracker(self.gcda_path)

    def load_seeds_into_corpus(self) -> int:
        """
        Load and validate the seed file. The parser provided by `sqlglot` doesn't cover the entire dialect of SQLite.
        For now, we want to start with a clean corpus, so we consider only the test cases with:
            (i) no parsing errors;
            (ii) no parsing warning (unsupported syntax to falls down to the generic Command);
            (iii) success execution after doing a parse + print cycle.
        """
        seeds: dict[str, str] = {}
        for filename in os.listdir(self.seed_dir):
            if filename.endswith('.sql'):
                with open(os.path.join(self.seed_dir, filename), 'r') as f:
                    seeds[filename] = "".join(f.read().splitlines())
        if not seeds:
            logger.error(f"No seed files found in {self.seed_dir}.")
            raise FileNotFoundError(f"No seed files found in {self.seed_dir}.")
        logger.bind(terminal=True).info(f"Loading and validating {len(seeds)} seed files from {self.seed_dir}.")

        skipping_files = 0
        for (filename, query) in seeds.items():
            try:
                result_initial = self.executor.execute(query)
                if result_initial["status"] != "SUCCESS":
                    skipping_files += 1
                    self.report_execution_result(result_initial, query, filename)
                    continue

                query_tree = sqlglot.parse_one(query, read=SQL_DIALECT)
                if isinstance(query_tree, exp.Block):
                    if any(isinstance(expr, exp.Command) for expr in query_tree.expressions):
                        skipping_files += 1
                        logger.warning(
                            f"Failed to parse seed file {filename}: Contains statement with unsupported syntax, "
                            "and the parser fell back to parse it as a Command."
                        )
                        continue
                
                query_printed = query_tree.sql(dialect=SQL_DIALECT)
                result_after = self.executor.execute(query_printed)
                if result_after["status"] != "SUCCESS":
                    skipping_files += 1
                    self.report_execution_result(result_after, query_printed, filename)
                    continue
                
                self.report_query(query_printed, id=filename, parent="None")
                self.corpus.append((query_printed, filename))
                self.generated_queries.add(query_printed)
            except sqlglot.errors.ParseError as e:
                skipping_files += 1
                logger.warning(f"Failed to parse seed file {filename}: {e.errors[0]}.")
        return skipping_files
    
    def pretty_print(self, query: str) -> str:
        query_parsed = sqlglot.parse_one(query, read=SQL_DIALECT)
        if isinstance(query_parsed, exp.Block):
            return ";\n".join(expr.sql(dialect=SQL_DIALECT) for expr in query_parsed.expressions) + ";"
        return query_parsed.sql(dialect=SQL_DIALECT)

    def report_query(self, query: str, id: str, parent: str) -> None:
        """Helpful to keep track of the mutation tree and the queries that are being executed."""
        logger.bind(query=True).info(f"--- index: {id}; parent: {parent}\n{self.pretty_print(query)}")

    def report_execution_result(self, result: ExecutionResult, query: str, query_id: str) -> None:
        pretty_output = "\n".join([
            f"Execution result with status {result['status']}!",
            f"Description:\n{result['description']}",
            f"Query: ID {query_id}\n{self.pretty_print(query)}"
        ])
        if result["status"] != "SUCCESS":
            logger.error(pretty_output)
        else:
            logger.info(pretty_output)

    def run(self, max_queries: int = 10000) -> None:
        logging_dir = setup_logging()
        logger.bind(terminal=True).info("Starting SQL fuzzer.")
        logger.bind(terminal=True).info(f"Details logs will be saved to directory {logging_dir}.")
        skipped_files = self.load_seeds_into_corpus()
        if skipped_files > 0:
            logger.bind(terminal=True).warning(f"Skipped {skipped_files} seed files due to sqlglot (parsing errors or unsupported syntax)" +
                                               " or due to them already being unsuccessful.")
        
        logger.bind(terminal=True).info(f"Starting mutations with initial corpus size: {len(self.corpus)}.")
        queries_generated_count = 0
        display = StatsDisplay(max_queries)
        # Clear gcda file if it exists to start fresh for this fuzzing campaign.
        if os.path.exists(self.gcda_path):
            os.remove(self.gcda_path)
        try:
            while True:
                if queries_generated_count >= max_queries or not self.corpus:
                    break
                # Pick a random query from the corpus.
                chosen_id = random.choice(range(len(self.corpus)))
                base_query, base_query_id = self.corpus[chosen_id]
                logger.debug(f"Selected query ID {base_query_id} from the corpus for mutation.")
                mutated_queries = self.mutator.mutate(base_query, base_query_id, 10)
                if not mutated_queries:
                    logger.debug(f"No mutations left for query ID {base_query_id}. Removing it from the corpus.")
                    self.corpus.pop(chosen_id)
                    continue
                for mutated_query in mutated_queries:
                    if mutated_query in self.generated_queries:
                        continue
                    queries_generated_count += 1
                    self.report_query(mutated_query, id=str(queries_generated_count), parent=base_query_id)
                    result = self.executor.execute(mutated_query)
                    self.statistics.collect(result)
                    self.generated_queries.add(mutated_query)
                    # Check for new coverage directly from the .gcda file.
                    new_coverage = self.coverage_tracker.check_for_new_coverage()
                    if result["status"] != "SUCCESS":
                        self.report_execution_result(result, mutated_query, str(queries_generated_count))
                    elif new_coverage:
                        current_cov = self.coverage_tracker.get_coverage_count()
                        logger.debug(f"New coverage discovered at query {queries_generated_count}! Total basic blocks hit: {current_cov}. Adding to corpus.")
                        self.corpus.append((mutated_query, str(queries_generated_count)))
                    display.update(len(self.corpus), queries_generated_count, self.statistics, self.coverage_tracker.get_coverage_count())
        except KeyboardInterrupt:
            logger.info("Fuzzing interrupted by user.")
        finally:
            display.finish()
            logger.bind(terminal=True).info(f"Finished generating {self.statistics.queries_generated} queries. Final corpus size: {len(self.corpus)}.")
            logger.bind(terminal=True).info(get_performance_stats(self.statistics.queries_generated))
            logger.bind(terminal=True).info(self.statistics.get_validity_stats())
            logger.bind(terminal=True).info(self.statistics.get_top30_keywords_stats(list(self.generated_queries)))
            # Run final evaluation using the collected corpus
            self.run_final_evaluation()           
     
    def run_final_evaluation(self):
        """
        Run the final evaluation to report Line, Branch, and Function coverage.
        As requested, this executes the saved corpus sequentially to find the final coverage.
        """
        logger.bind(terminal=True).info("Running sequential execution of corpus for final gcov evaluation...")
        
        # First, remove existing gcda to start fresh for the final evaluation
        if os.path.exists(self.gcda_path):
            os.remove(self.gcda_path)
            
        # Re-execute all generated queries sequentially
        for i, query in enumerate(self.generated_queries):
            self.executor.execute(query)
            
        # Call lcov
        run_final_lcov_evaluation("/home/test/sqlite3-src")