CREATE TABLE t1 (a INTEGER, b INTEGER);
CREATE TABLE t2 (c INTEGER, d INTEGER);
CREATE TABLE t3 (e TEXT, f TEXT);
INSERT INTO t1 VALUES (1, 1);
INSERT INTO t2 VALUES (1, 2);
INSERT INTO t3 VALUES ('abc', 'def');
SELECT * FROM t1 FULL JOIN t2 ON (t2.c = t1.a) INNER JOIN t3 ON (t2.d IS NULL);